### ISSUE TITLE
 Error: hoop: SHA256 mismatch

### ISSUE THREAD

**Issue by JerryMacedoCastro** [hoophq/hoopcli#1]
Hello, 

I'm trying to install hoop cli on wsl ubuntu but I'm getting the error->  Error: hoop: SHA256 mismatch
![image](https://github.com/hoophq/hoopcli/assets/39466788/d5d26934-5c93-4fe9-a560-121b49f4c844)

The SHA256 genereted is for a ARM processor wich is not my case as you can see 
![image](https://github.com/hoophq/hoopcli/assets/39466788/dcee7ec2-6d95-4c3c-ac94-3743dd951b95)
![image](https://github.com/hoophq/hoopcli/assets/39466788/161adc5e-d5a2-4a34-979d-dd72526f3a67)

Can I get some help here?

**Comment by sandromello** [comment]
Hey Jerry, thank you for reporting this problem. We found a problem when generating the brew recipe for linux distribution. It should be fixed in the upcoming releases (1.20.7+).

Check our documentation to see how to install and upgrade the command line:
https://hoop.dev/docs/connect-and-manage/hoop-cli
